default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: hrm
  password: ENV['pg_password']

development:
  <<: *default
  database: hrm_development

test:
  <<: *default
  database: hrm_test

production:
  <<: *default
  database: hrm_production
